# Exercise 01
# Please don't write any of the code for this exercise in this file, use a separate script to run the main program
# and separate files for the classes.
# 1. Copy-paste the lesson.rb code (you may add a Gemfile and remove the 'require's) into a new file called `scrape_rottent_tomatoes.rb`
# 2. Refactor the existing code by adding the necessary classes to hold the scraped data and fill the 'movies' array with objects instead of hashes (please use as many new files as needed to keep the classes in their own files).
# 3. In the `scrape_rotten_tomatoes.rb` script, get and report the **total sales generated by all the movies** by using methods that you write for the classes you are using.
# 4. In the same script and also using methods from your custom classes, get and report the **average movie score**.


require './scraping'
require './movie'


class RottentTomatoes
  include Scraping

  attr_reader :movies
  def initialize(url)
    @url = url
    @movies = []
  end

  def scrape
    @scrape ||= Scraping.new(get(@url))    
  end

  def assign
    scrape.iterate_dom('#Top-Box-Office tr') do |node|
      movie = Movie.new
      movie.name = node.css(movie.name_node).text
      movie.score = node.css(movie.score_node).text
      movie.sale = node.css(movie.sale_node).text

      @movies << movie
    end
  end

end


tmp = RottentTomatoes.new("http://www.rottentomatoes.com/")
tmp.assign
tmp.movies.each do |movie|
  print "#{movie.name} - #{movie.sale} - #{movie.score}"
  
end
